name: Deploy BE Production to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  call-deploy-be:
    permissions:
      contents: "read"
      id-token: "write"
      
    uses: ./.github/workflows/deploy-be.yml
    with:
      environment: production
    secrets: inherit
