name: Deploy BE to Cloud Run

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Build BE image and deploy to Cloud Run
        run: |
          cd backend
          docker build -t dapp-be-image .
          gcloud run deploy dapp-be-${{ inputs.environment }} --source . --region=asia-southeast1 --port=5000 --service-account=${{ secrets.SERVICE_ACCOUNT }}
