name: Deploy BE Staging to Cloud Run

on:
  pull_request:
    branches:
      - main

jobs:
  call-deploy-be:
    permissions:
      contents: "read"
      id-token: "write"
      
    uses: ./.github/workflows/deploy-be.yml
    with:
      environment: staging
    secrets: inherit
