name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  call-deploy-fe:
    permissions:
      contents: "read"
      id-token: "write"

    uses: ./.github/workflows/deploy-fe.yml
    with:
      environment: production
      network-name: bneMainnet
    secrets: inherit
